### ISSUE TITLE
Horizontal line artifacts in MS Edge browser

### ISSUE THREAD

**Issue by drk4** [scottaohara/accessible_modal_window#10] opened 2019-02-25 17:02 UTC
I am running into an issue which is preventing use of this otherwise great script.

On Win10 / Edge when a modal is large enough to require scrolling, horizontal 1px lines appear when revealing content 'on-scroll'

It looks like it could be this issue?
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9011176/

can anyone else replicate this and is there a workaround?

**Comment by scottaohara** [comment] 2019-02-25 17:36
Interesting.  I can't reproduce the issue on my windows 10 machine, but per that bug thread, looks like it's an issue with Edge.

In testing with my script, are you using the default styles provided, or adding your own and then running into the issue?

**Comment by drk4** [comment] 2019-02-25 18:04
After spending some time stripping back your test pages i've found that the line
`*:focus{outline: 2px solid #921c2b; outline-offset: 2px; text-decoration: none;}` in the demo.css seems to prevent the issue on your examples.

if this line is removed then the bug appears

**Comment by scottaohara** [comment] 2019-02-25 18:09
so sounds like you found a potential work around for Edge's bug here.

might you try adding this to your styles, and try adding a transparent color to keep the outline invisible?

Closing the issue because it's not an issue with my script.  Might be worth a note in the CSS though to mention this Edge bug and that this fixes it for some reason?

**Closed by scottaohara** 2019-02-25 18:09 UTC
